"""ilk sema 11 tablo

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 17:04:50.747116
"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector kolonları için)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate eklentileri görmez; embedding kolonları için şart (pgvector kurulu olmalı)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('sehir', sa.String(), nullable=True),
    sa.Column('musaitlik', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kullanici'))
    )
    op.create_table('kurum',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('sektor', sa.String(), nullable=True),
    sa.Column('sehir', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kurum'))
    )
    op.create_table('ihtiyac_karti',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kurum_id', sa.UUID(), nullable=False),
    sa.Column('problem_tanimi', sa.Text(), nullable=False),
    sa.Column('basari_kriteri', sa.Text(), nullable=True),
    sa.Column('kisitlar', sa.Text(), nullable=True),
    sa.Column('sehir_tercihi', sa.String(), nullable=True),
    sa.Column('musaitlik_tercihi', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], name=op.f('fk_ihtiyac_karti_kurum_id_kurum'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ihtiyac_karti'))
    )
    op.create_index(op.f('ix_ihtiyac_karti_kurum_id'), 'ihtiyac_karti', ['kurum_id'], unique=False)
    op.create_table('yetenek_karti',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=False),
    sa.Column('rol_alani', sa.String(), nullable=False),
    sa.Column('deneyim_seviyesi', sa.String(), nullable=False),
    sa.Column('sektor_ilgi_alani', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('araclar_teknolojiler', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('kanit_bekleyen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('versiyon', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], name=op.f('fk_yetenek_karti_kullanici_id_kullanici'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yetenek_karti'))
    )
    op.create_index(op.f('ix_yetenek_karti_kullanici_id'), 'yetenek_karti', ['kullanici_id'], unique=False)
    op.create_table('eslesme',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('yetenek_karti_id', sa.UUID(), nullable=False),
    sa.Column('ihtiyac_karti_id', sa.UUID(), nullable=False),
    sa.Column('skor', sa.Float(), nullable=False),
    sa.Column('gerekce_metni', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(), nullable=False),
    sa.Column('son_aktivite_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ihtiyac_karti_id'], ['ihtiyac_karti.id'], name=op.f('fk_eslesme_ihtiyac_karti_id_ihtiyac_karti'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yetenek_karti_id'], ['yetenek_karti.id'], name=op.f('fk_eslesme_yetenek_karti_id_yetenek_karti'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eslesme'))
    )
    op.create_index(op.f('ix_eslesme_ihtiyac_karti_id'), 'eslesme', ['ihtiyac_karti_id'], unique=False)
    op.create_index(op.f('ix_eslesme_yetenek_karti_id'), 'eslesme', ['yetenek_karti_id'], unique=False)
    op.create_table('somut_cikti',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('yetenek_karti_id', sa.UUID(), nullable=False),
    sa.Column('baslik', sa.String(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kanit_linki', sa.String(), nullable=True),
    sa.Column('kanit_turu', sa.String(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['yetenek_karti_id'], ['yetenek_karti.id'], name=op.f('fk_somut_cikti_yetenek_karti_id_yetenek_karti'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_somut_cikti'))
    )
    op.create_index(op.f('ix_somut_cikti_yetenek_karti_id'), 'somut_cikti', ['yetenek_karti_id'], unique=False)
    op.create_table('canlilik_olayi',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('eslesme_id', sa.UUID(), nullable=False),
    sa.Column('tetiklenme_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tur', sa.String(), nullable=False),
    sa.Column('mesaj_metni', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eslesme_id'], ['eslesme.id'], name=op.f('fk_canlilik_olayi_eslesme_id_eslesme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canlilik_olayi'))
    )
    op.create_index(op.f('ix_canlilik_olayi_eslesme_id'), 'canlilik_olayi', ['eslesme_id'], unique=False)
    op.create_table('guven_skoru',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('somut_cikti_id', sa.UUID(), nullable=False),
    sa.Column('kanit_orijinalligi', sa.Integer(), nullable=False),
    sa.Column('sonuc_olculebilirligi', sa.Integer(), nullable=False),
    sa.Column('rol_netligi', sa.Integer(), nullable=False),
    sa.Column('ucuncu_taraf_onayi', sa.Integer(), nullable=False),
    sa.Column('gerekce_metni', sa.Text(), nullable=True),
    sa.CheckConstraint('kanit_orijinalligi BETWEEN 0 AND 3', name=op.f('ck_guven_skoru_kanit_orijinalligi_aralik')),
    sa.CheckConstraint('rol_netligi BETWEEN 0 AND 3', name=op.f('ck_guven_skoru_rol_netligi_aralik')),
    sa.CheckConstraint('sonuc_olculebilirligi BETWEEN 0 AND 3', name=op.f('ck_guven_skoru_sonuc_olculebilirligi_aralik')),
    sa.CheckConstraint('ucuncu_taraf_onayi BETWEEN 0 AND 3', name=op.f('ck_guven_skoru_ucuncu_taraf_onayi_aralik')),
    sa.ForeignKeyConstraint(['somut_cikti_id'], ['somut_cikti.id'], name=op.f('fk_guven_skoru_somut_cikti_id_somut_cikti'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guven_skoru')),
    sa.UniqueConstraint('somut_cikti_id', name=op.f('uq_guven_skoru_somut_cikti_id'))
    )
    op.create_table('isbirligi',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('eslesme_id', sa.UUID(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eslesme_id'], ['eslesme.id'], name=op.f('fk_isbirligi_eslesme_id_eslesme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isbirligi')),
    sa.UniqueConstraint('eslesme_id', name=op.f('uq_isbirligi_eslesme_id'))
    )
    op.create_table('referans_istegi',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('somut_cikti_id', sa.UUID(), nullable=False),
    sa.Column('referans_email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('durum', sa.String(), server_default=sa.text("'bekliyor'"), nullable=False),
    sa.Column('yanit_metni', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['somut_cikti_id'], ['somut_cikti.id'], name=op.f('fk_referans_istegi_somut_cikti_id_somut_cikti'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referans_istegi')),
    sa.UniqueConstraint('token', name=op.f('uq_referans_istegi_token'))
    )
    op.create_index(op.f('ix_referans_istegi_somut_cikti_id'), 'referans_istegi', ['somut_cikti_id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('isbirligi_id', sa.UUID(), nullable=False),
    sa.Column('baslik', sa.String(), nullable=False),
    sa.Column('hedef_tarih', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['isbirligi_id'], ['isbirligi.id'], name=op.f('fk_milestone_isbirligi_id_isbirligi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_index(op.f('ix_milestone_isbirligi_id'), 'milestone', ['isbirligi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestone_isbirligi_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_referans_istegi_somut_cikti_id'), table_name='referans_istegi')
    op.drop_table('referans_istegi')
    op.drop_table('isbirligi')
    op.drop_table('guven_skoru')
    op.drop_index(op.f('ix_canlilik_olayi_eslesme_id'), table_name='canlilik_olayi')
    op.drop_table('canlilik_olayi')
    op.drop_index(op.f('ix_somut_cikti_yetenek_karti_id'), table_name='somut_cikti')
    op.drop_table('somut_cikti')
    op.drop_index(op.f('ix_eslesme_yetenek_karti_id'), table_name='eslesme')
    op.drop_index(op.f('ix_eslesme_ihtiyac_karti_id'), table_name='eslesme')
    op.drop_table('eslesme')
    op.drop_index(op.f('ix_yetenek_karti_kullanici_id'), table_name='yetenek_karti')
    op.drop_table('yetenek_karti')
    op.drop_index(op.f('ix_ihtiyac_karti_kurum_id'), table_name='ihtiyac_karti')
    op.drop_table('ihtiyac_karti')
    op.drop_table('kurum')
    op.drop_table('kullanici')
    # ### end Alembic commands ###
    # "vector" eklentisi bilerek düşürülmüyor: veritabanı düzeyinde paylaşılan bir kaynak
