"""calisma modeli alanlari

Konum ile çalışma modeli ayrıldı (LinkedIn/Kariyer.net deseni). Önce şehir
listesine "Uzaktan / fark etmez" diye bir seçenek konmuştu; bu "İstanbul'da
ama hibrit" gibi çok sık bir durumu ifade edilemez kılıyordu.

Veri taşıma: şehri "uzaktan" olan kayıtlarda şehir boşaltılıp bilgi yeni
alana yazılıyor.

Revision ID: 0e3cd1cd3fdf
Revises: a1c4f7e2b903
Create Date: 2026-09-24 23:19:26.888322
"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector kolonları için)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0e3cd1cd3fdf'
down_revision: str | None = 'a1c4f7e2b903'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihtiyac_karti', sa.Column('calisma_modeli', sa.String(), nullable=True))
    op.add_column('kullanici', sa.Column('calisma_modelleri', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))

    # Eski "uzaktan" şehir değerleri yeni alana taşınıyor.
    op.execute(
        "UPDATE kullanici SET calisma_modelleri = ARRAY['uzaktan']::text[], sehir = NULL "
        "WHERE sehir = 'uzaktan'"
    )
    op.execute(
        "UPDATE ihtiyac_karti SET calisma_modeli = 'uzaktan', sehir_tercihi = NULL "
        "WHERE sehir_tercihi = 'uzaktan'"
    )


def downgrade() -> None:
    # Taşınan "uzaktan" bilgisi şehir alanına geri yazılıyor ki veri kaybolmasın.
    op.execute("UPDATE kullanici SET sehir = 'uzaktan' WHERE 'uzaktan' = ANY(calisma_modelleri)")
    op.execute(
        "UPDATE ihtiyac_karti SET sehir_tercihi = 'uzaktan' WHERE calisma_modeli = 'uzaktan'"
    )
    op.drop_column('kullanici', 'calisma_modelleri')
    op.drop_column('ihtiyac_karti', 'calisma_modeli')
