"""olusturma_tarihi: ihtiyac_karti ve referans_istegi

Revision ID: bbfac2425ba7
Revises: cab64a993783
Create Date: 2026-09-24 10:39:57.636208
"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector kolonları için)
import sqlalchemy as sa
from alembic import op


revision: str = 'bbfac2425ba7'
down_revision: str | None = 'cab64a993783'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihtiyac_karti', sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referans_istegi', sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referans_istegi', 'olusturma_tarihi')
    op.drop_column('ihtiyac_karti', 'olusturma_tarihi')
    # ### end Alembic commands ###
